import Foundation

struct AppProfileBinding: Codable, Identifiable {
    let id: UUID
    var command: String
    var profileName: String
    var description: String?

    init(id: UUID = UUID(), command: String, profileName: String, description: String? = nil) {
        self.id = id
        self.command = command
        self.profileName = profileName
        self.description = description
    }
}

class AppProfileBindingManager {
    static let shared = AppProfileBindingManager()

    private let bindingsFile: URL
    private var bindings: [AppProfileBinding] = []

    private init() {
        let appSupportDir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let appDir = appSupportDir.appendingPathComponent("AWS CLI Gateway")

        if !FileManager.default.fileExists(atPath: appDir.path) {
            try? FileManager.default.createDirectory(at: appDir, withIntermediateDirectories: true)
        }

        bindingsFile = appDir.appendingPathComponent("app_profile_bindings.json")
        loadBindings()
    }

    // MARK: - Public API

    func getBindings() -> [AppProfileBinding] {
        return bindings
    }

    func getProfile(forCommand command: String) -> String? {
        return bindings.first(where: { $0.command == command })?.profileName
    }

    func addBinding(command: String, profileName: String, description: String? = nil) {
        if let index = bindings.firstIndex(where: { $0.command == command }) {
            bindings[index].profileName = profileName
            bindings[index].description = description
        } else {
            bindings.append(AppProfileBinding(command: command, profileName: profileName, description: description))
        }
        saveBindings()
    }

    func removeBinding(forCommand command: String) {
        bindings.removeAll(where: { $0.command == command })
        saveBindings()
    }

    func removeBinding(id: UUID) {
        bindings.removeAll(where: { $0.id == id })
        saveBindings()
    }

    /// Generates a shell integration script that wraps bound commands with the correct AWS_PROFILE
    func generateShellIntegration() -> String {
        var script = """
        #!/bin/bash
        # AWS CLI Gateway — App Profile Bindings
        # Source this file in your .zshrc or .bashrc:
        #   source "$HOME/Library/Application Support/AWS CLI Gateway/profile_bindings.sh"
        #
        # Auto-generated by AWS CLI Gateway. Do not edit manually.
        # Manage bindings via the app's Tools & Settings menu.

        _GATEWAY_BINDINGS_FILE="$HOME/Library/Application Support/AWS CLI Gateway/app_profile_bindings.json"

        """

        for binding in bindings {
            let safe = binding.command.replacingOccurrences(of: "'", with: "'\\''")
            let desc = binding.description ?? "Bound to \(binding.profileName) via AWS CLI Gateway"
            script += """

            # \(desc)
            \(binding.command)() {
                AWS_PROFILE='\(binding.profileName)' command \(safe) "$@"
            }

            """
        }

        return script
    }

    /// Writes the shell integration script to Application Support
    func installShellIntegration() throws -> URL {
        let scriptContent = generateShellIntegration()
        let scriptPath = bindingsFile.deletingLastPathComponent().appendingPathComponent("profile_bindings.sh")
        try scriptContent.write(to: scriptPath, atomically: true, encoding: .utf8)

        // Make executable
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: scriptPath.path)

        return scriptPath
    }

    // MARK: - Private

    private func loadBindings() {
        guard FileManager.default.fileExists(atPath: bindingsFile.path) else { return }
        do {
            let data = try Data(contentsOf: bindingsFile)
            bindings = try JSONDecoder().decode([AppProfileBinding].self, from: data)
        } catch {
            print("AppProfileBindingManager: Error loading bindings: \(error)")
            bindings = []
        }
    }

    private func saveBindings() {
        do {
            let encoder = JSONEncoder()
            encoder.outputFormatting = .prettyPrinted
            let data = try encoder.encode(bindings)
            try data.write(to: bindingsFile)

            // Regenerate shell integration script
            _ = try? installShellIntegration()
        } catch {
            print("AppProfileBindingManager: Error saving bindings: \(error)")
        }
    }
}
